### ISSUE TITLE
Error while trying download

### ISSUE THREAD

**Issue by thawancomt** [anishomsy/apkpure#3]
```
https://d.apkpure.com/b/APK/com.dts.freefireth?versionCode=2019117297
Downloading Latest
Traceback (most recent call last):
  File "c:\Users\thawa\Documents\GitHub\apkpureAPI\apkpure\apkpure.py", line 190, in download
    callback = self.downloader(url)
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\thawa\Documents\GitHub\apkpureAPI\apkpure\apkpure.py", line 211, in downloader
    d = response.headers['content-disposition']
        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'content-disposition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\thawa\Documents\GitHub\apkpureAPI\usage.py", line 7, in <module>
    allResults = api.download('free fire')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\thawa\Documents\GitHub\apkpureAPI\apkpure\apkpure.py", line 193, in download
    return self.downloader(url)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\thawa\Documents\GitHub\apkpureAPI\apkpure\apkpure.py", line 211, in downloader
    d = response.headers['content-disposition']
        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'content-disposition'
```

**Comment by anishomsy** [comment]
I fixed this issue. Please update the package and see if the problem is fixed
